version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      
    volumes:
      # This is where VS Code should expect to find your project's source code and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"  

    environment:
      - APP_PORT=7030
      - APP_DEV_MODE=true
      - REDIS_HOST=redis

    # Runs app on the same network as the service container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:redis

  redis:
    image: redis:alpine
    logging:
      driver: "none"
